### PR TITLE
Synchronize postman collection ids

### PR DESCRIPTION
**Pull request by clement-hvt**
Synchronizes the ids of the collection to be modified with those of the newly generated collection.
This feature prevents the destination collection from being overwritten. The pull requests are therefore not erroneous (see the updated readme).

### CODE REVIEW

**Comment by thim81** [comment]
hi @Xainon ,

We just saw that you closed the PR? Could you share why?
We were planning on reviewing it, to have it included in the next release.

**Comment by Xainon** [comment]
hi, I have a problem with response objects and I don't see how to manage them. My problem is with responses that do not have an example in their properties and therefore with values generated with a faker. Either I don't replace their ID and when I make a pull request then I have a deletion of the response then a creation, or with the replaceId function I don't have a deletion and modification but a conflict. So I don't see how to deal with this dilemma.

**Comment by Xainon** [comment]
I think the problem can be solved with the `exampleParametersResolution` in the postman config to disable the faker. Should it default to `Schema` if my new option is set to `true` ?

**Comment by thim81** [comment]
hi @Xainon 

I understand what you are trying to solve with this PR.

Question: Is there not a risk, that if the requests are actually changed, but the IDs are the same; Postman will still keep the older requests and not take/show the updates? This would expose the incorrect requests in your online Postman collection and everybody who uses them?

**Comment by Xainon** [comment]
hi @thim81,
after dozens of calls to portman with this option i have not encountered this problem and the elements that have changed following portman are well detected.
Do you see the question I was asking about the sample responses?

**Comment by thim81** [comment]
> I think the problem can be solved with the `exampleParametersResolution: Schema` in the postman config to disable the faker. Should we force the value to be `Schema` if my new option(`syncPostmanCollectionIds`) is set to `true` ? The `SchemaFaker` option can solve the problem but is not yet available ([here](https://github.com/postmanlabs/openapi-to-postman/blob/b2669837a9ee8c855b161ac3154905253d14c3d2/lib/schemapack.js#L60)).

Given that to be able to create a "stable" postman collection, it is not ideal that the schema faker function generates new values each conversion, it would make sense to force the disable `schemaFaker` option when the `syncPostmanCollectionIds` is used.

**Comment by thim81** [comment]
A small request, can you also add the new CLI option in the general readme?
If you are building-in the forced disable `SchemaFaker`, I would mention it with the CLI option in the readme so that the users are aware of the impact.

**Review by nicklloyd — APPROVED** [review]

**Comment by Xainon** [comment]
Do you want me to make the change? 
As the option is currently unavailable, it is necessary to set exampleParametersResolution to true so that the type is set to example rather than a faker string.

**Comment by thim81** [comment]
@Xainon 
If it is possible to force the behaviour (without the `schemaFaker` option being available), like you tried with:
> after dozens of calls to portman with this option i have not encountered this problem and the elements that have changed following portman are well detected.

If it is not possible, we need to include it in the read me to guide the users to use the correct configuration.

**Comment by thim81** [comment]
hi @clement-hvt 

The PR looks fine and will be merged.
After the merge, I'm going to move the last changes to an example section to keep the command reference more compact.

**Pull request merged**
