### PR TITLE
stripResponseExamples CLI option

### PR DESCRIPTION
**Pull request by thim81**
Added stripResponseExamples CLI option

### CODE REVIEW

**Comment by thim81** [comment]
@nicklloyd any suggestion how & where to test this?

**Comment by thim81** [comment]
Linked to #179

**Comment by nicklloyd** [comment]
> 

Shit now that I see the code, think it _does_ belong in globals :/

**Comment by nicklloyd** [comment]
I understand if you don't want to move now that you've implemented, just your initial thinking was correct

**Comment by thim81** [comment]
I'll move it into globals and make it a function.
It is a simple lift & shift + test

**Pull request merged**
