### PR TITLE
Add Unknown Formats CLI Option

### PR DESCRIPTION
**Pull request by George-lewis**
Hi all, this PR adds a CLI option that enables adding additional formats to the `unknownFormats` field of the generated Json schema tests. I'm using Portman to convert some Openapi spec that uses formats the validator doesn't like, and so need this escape hatch. Custom validators would work too, but I'm not sure if that's possible.

Please let me know what you think

### CODE REVIEW

**Comment by thim81** [comment]
@George-lewis Thanks for taking the time to create a well developed PR.

The feature addition is definitely useful and the implementation is backward compatible.

I might have only minor, optional request, would you mind including the CLI option in the readme?
If you don't feel comfortable, no worries, we will add the option in the readme after the merge.

**Comment by George-lewis** [comment]
@thim81 Thanks!

I'll take a look at the readme and see what I can do.

As for the parameter, you can find the docs here: https://github.com/yargs/yargs/blob/main/docs/api.md#array

Basically, it's used like `portman -l .. -o .. -extraUnknownFormats ulid abc xyz`, or like `portman -l .. -o .. -extraUnknownFormats ulid -extraUnknownFormats abc` and so on (I like the first way better)

**Comment by nicklloyd** [comment]
Nice addition 🤘🏻

**Comment by thim81** [comment]
In the readme, there is "CLI options" where we display examples like: https://github.com/apideck-libraries/portman#skip-tests-and-just-generate-collection

**Comment by George-lewis** [comment]
I've added an example. If you want to reword anything feel free to push to my branch, or change it after merge

**Review by thim81 — APPROVED** [review]
Looks very good.

**Comment by thim81** [comment]
@George-lewis We just released Portman v1.18.0, which includes your contribution

We appreciate that you the took the time to create the PR. Thank you!

**Pull request merged**
