### PR TITLE
ContentTest - Added "oneOf" check

### PR DESCRIPTION
**Pull request by thim81**
ContentTest - Added "oneOf" check for "responseBody" & "responseHeader"

### CODE REVIEW

**Comment by thim81** [comment]
Linked to #313

**Comment by nicklloyd** [comment]
nice!

**Comment by thim81** [comment]
@nicklloyd Are you ok with the "oneOf" option? or prefer a different term for the check?

**Comment by nicklloyd** [comment]
LGTM! 🤘🏻

**Review by nicklloyd — APPROVED** [review]

**Pull request merged**
