### PR TITLE
Fix test status code in contract test #238

### PR DESCRIPTION
**Pull request by AliKhalili**
A tiny fix, Linked to [#238](https://github.com/apideck-libraries/portman/discussions/238)

### CODE REVIEW

**Comment by thim81** [comment]
@AliKhalili I tested your PR, it does the trick.

I'm going to see if I can add a test so can have it covered in the future.

**Review by thim81 — APPROVED** [review]

**Comment by thim81** [comment]
@AliKhalili I'm not a coder by nature and I don't fully understand how your code change solved the issue.

before:
`const statusCodeSetting = optStatusCode  as StatusCode`

after:
`const statusCodeSetting = { ...optStatusCode } as StatusCode`

Would you mind enlighten me what is the difference?

**Comment by AliKhalili** [comment]
@thim81 
Your codes are very well implemented and I like your implementation. I learn many things from Portman source code.
At this line of code you create a new `statusCodeSetting` variable but it just a new reference to the old variable `optStatusCode `, so when we changed the `statusCodeSetting`, it also changes the value of `optStatusCode `. for solving this issue we need to create a new object by copy the value of all properties one by one which we can do this by spread syntax.
When a variable refers to an object (including arrays), the "value" is a reference to the object.
https://dmitripavlutin.com/static/21075d0959751add1730239d141bbe87/42163/references-2.png

**Comment by thim81** [comment]
Thanks for explaining and I now see that indeed it was a "reference". 
I must have missed that + I think we might run into some more referenced variables. 

Thanks again for your PR

**Pull request merged**
